-
  name: Test Connectivity to target server
  hosts: webserver
  become: yes
  become_user: root
  tasks:
    - name: Creates directory
      file:
         path: /var/www/inc
         state: directory
         mode: 0777
    - name: Ansible create file if it doesn't exist example
      file:
        path: "/var/www/inc/dbinfo.inc"
        state: touch
    
